services:
  marktplaats-notif:
    image: ghcr.io/gideonbear/marktplaats-notif
    container_name: marktplaats-notif
    volumes:
      - ./config:/config
    environment:
      - PORT=1301
    ports:
      - 1301:1301
    restart: unless-stopped
