services:
  marktplaats-notif:
    image: ghcr.io/gideonbear/marktplaats-notif
    container_name: marktplaats-notif
    volumes:
      - ./config:/config
    environment:
      - PORT=1234
    ports:
      - 1234:1234
    restart: unless-stopped
